name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [graalvm-ce-java11@20.3.0]
        rust: [1.40.0]

    steps:
    - uses: actions/checkout@v1
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: olafurpg/setup-scala@v10
      with:
        java-version: ${{ matrix.java }}
    - name: Run tests
      run: sbt test
